// Get ALL Coins
export const FETCH_COINS_REQUEST = "FETCH_COINS_REQUEST"
export const FETCH_COINS_SUCCESS = "FETCH_COINS_SUCCESS"
export const FETCH_COINS_FAILURE = "FETCH_COINS_FAILURE"
export const FILTER_COINS_BY_NAME = "FILTER_COINS_BY_NAME"
export const FILTER_COINS_BY_CHANGE_PRICE = "FILTER_COINS_BY_CHANGE_PRICE"

// Get Specific Coin by ID
export const FETCH_COIN_REQUEST = "FETCH_COIN_REQUEST"
export const FETCH_COIN_SUCCESS = "FETCH_COIN_SUCCESS"
export const FETCH_COIN_FAILURE = "FETCH_COIN_FAILURE"
